spring:
    datasource:
        username: root
        password: Ha@0703750755
        url: jdbc:mysql://127.0.0.1:3306/movieDb
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true